version: "3.9"

volumes:
  db:
    driver: local
  redis:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine3.16
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
    ports:
      - "6379:6379"